### ISSUE TITLE
 clouseau-status-flags - Do not update when release is tiny 

### ISSUE THREAD

**Issue by sylvestre** [mozilla/clouseau#87] opened 2016-10-03 14:09 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1303967#c9
With 3 crashes, not sure it was worth updating it

**Comment by marco-c** [comment] 2016-10-03 14:14
This could also help with false positives. The problem is deciding what is the minimum number of crashes that we should consider important enough.

**Comment by marco-c** [comment] 2016-10-19 19:14
I've seen a few more cases of this today.

**Comment by calixteman** [comment] 2016-11-21 10:39
Fixed in commit #107

**Closed as completed by calixteman** 2016-11-21 10:39 UTC
