### ISSUE TITLE
Example of a bug where I'd like the bot to update

### ISSUE THREAD

**Issue by lizzard** [mozilla/clouseau#78] opened 2016-09-02 22:46 UTC
This bug could definitely use a visit from clouseau. Top crash for android and high volume, also a startup crash. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1283629

**Comment by sylvestre** [comment] 2016-09-03 08:54
Duplicate of #71
I don't think we should use github issues for this kind of request :)

**Closed as completed by sylvestre** 2016-09-03 08:54 UTC
